export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const INVALID_PAGE = 'INVALID_PAGE';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS';
